import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@solana/wallet-adapter-react-ui/styles.css";
import {CivicPassProvider} from "@/app/components/CivicPassProvider";
import AppWalletProvider from "@/app/components/AppWalletProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <AppWalletProvider>
            <CivicPassProvider>
                {children}
            </CivicPassProvider>
        </AppWalletProvider>
        </body>
        </html>
    );
}
