import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
    EthersExtension,
    DynamicContextProvider,
    EthereumWalletConnectors,
} from "../lib/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <DynamicContextProvider
          settings={{
              environmentId: process.env.DYNAMIC_ENVIRONMENT_ID ?? "",
              walletConnectors: [EthereumWalletConnectors],
              walletConnectorExtensions: [EthersExtension],
          }}
      >
          <body className={inter.className}>{children}</body>
      </DynamicContextProvider>
      </html>
  );
}
